{% set name = "DeepGraph" %}
{% set version = "0.2.1" %}
{% set sha256 = "50b0079141777ec7b8809a3207f78c860cbed86867d5add3f7a31a8840f0bd81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  # git_url: https://github.com/deepgraph/deepgraph.git
  # git_rev: master  # {{ version }}
  # path: ../dist/{{ name }}-{{ version }}
  url: ../dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
  run:
    - python
    - numpy
    - pandas

test:
  files:
    - ../tests/test_DeepGraph.py
    - ../tests/test_CreateEdges.py
  requires:
    - deepgraph
    - pytest
    - numpy
    - pandas
    - scipy
    - networkx
  imports:
    - deepgraph
    - pytest
  commands:
    - conda install -y -p $PREFIX -c anaconda pytables
    - conda install -y -p $PREFIX graph-tool  # needs conda-forge and ostrokach channels
    - cd $PREFIX/../tests/
    - py.test -v

about:
  home: https://github.com/deepgraph/deepgraph
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Analyze Data with Pandas-based Networks.'
  description: |
    DeepGraph is a scalable, general-purpose data analysis package. It
    implements a network representation based on pandas DataFrames and
    provides methods to construct, partition and plot graphs, to interface
    with popular network packages and more.
  doc_url: https://deepgraph.readthedocs.io/

